
import React, { useState } from 'react';
import { Database, HardDrive, Check, Copy, Terminal, Shield, AlertTriangle, RefreshCw } from 'lucide-react';

const AdminSystemSetup: React.FC = () => {
  const [copiedSection, setCopiedSection] = useState<string | null>(null);

  const copyToClipboard = (text: string, section: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(section);
    setTimeout(() => setCopiedSection(null), 2000);
  };

  // SQL KHUSUS FIX REVIEW
  const fixReviewSQL = `-- FIX: Pastikan Publik bisa membaca Transaksi untuk memfilter Review
-- Jalankan ini jika Review tidak muncul di detail produk

-- 1. Reset Policy Transaksi
alter table public.transactions enable row level security;
drop policy if exists "Enable all access transactions" on public.transactions;
drop policy if exists "Public Read Transactions" on public.transactions;

-- 2. Buat Policy Baru (Buka Akses Baca/Tulis untuk Semua)
create policy "Enable all access transactions" on public.transactions 
for all using (true) with check (true);

-- 3. Reset Policy Reviews
alter table public.reviews enable row level security;
drop policy if exists "Enable all access reviews" on public.reviews;

create policy "Enable all access reviews" on public.reviews 
for all using (true) with check (true);`;

  // BAGIAN 1: TABEL UTAMA
  const coreSQL = `-- BAGIAN 1: Core Tables & Policies
create table if not exists public.transactions (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text,
  customer_whatsapp text,
  customer_campus text,
  customer_location text,
  customer_identity text,
  rental_date date,
  duration numeric,
  items jsonb,
  total_price numeric,
  fine_amount numeric default 0,
  amount_paid numeric default 0,
  payment_method text,
  payment_proof_url text,
  status text default 'pending'
);

alter table public.transactions enable row level security;
drop policy if exists "Enable all access transactions" on public.transactions;
create policy "Enable all access transactions" on public.transactions for all using (true) with check (true);

create table if not exists public.products (
  id text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  category text,
  price numeric default 0,
  "price3Days" numeric default 0,
  "price4Days" numeric default 0,
  "price5Days" numeric default 0,
  "price6Days" numeric default 0,
  "price7Days" numeric default 0,
  is_sale boolean default false,
  sale_price numeric default 0,
  stock numeric default 0,
  rented numeric default 0,
  damaged numeric default 0,
  image text,
  description text,
  package_items jsonb default '[]'::jsonb,
  sizes jsonb default '{}'::jsonb,
  colors text[],
  variants jsonb default '[]'::jsonb,
  color_images jsonb default '[]'::jsonb
);

alter table public.products enable row level security;
drop policy if exists "Enable all access products" on public.products;
create policy "Enable all access products" on public.products for all using (true) with check (true);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null
);

alter table public.categories enable row level security;
drop policy if exists "Enable all access categories" on public.categories;
create policy "Enable all access categories" on public.categories for all using (true) with check (true);`;

  // BAGIAN 2: FITUR TAMBAHAN
  const featuresSQL = `-- BAGIAN 2: Features (Reviews & Logs)
create table if not exists public.reviews (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  transaction_id text,
  customer_name text,
  rating numeric,
  comment text,
  is_public boolean default true
);

alter table public.reviews enable row level security;
drop policy if exists "Enable all access reviews" on public.reviews;
create policy "Enable all access reviews" on public.reviews for all using (true) with check (true);

create table if not exists public.payment_logs (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  transaction_id text,
  amount numeric not null,
  payment_method text,
  type text,
  description text,
  category text
);

alter table public.payment_logs enable row level security;
drop policy if exists "Enable all access logs" on public.payment_logs;
create policy "Enable all access logs" on public.payment_logs for all using (true) with check (true);`;

  // BAGIAN 3: STORAGE
  const storageSQL = `-- BAGIAN 3: Storage Buckets
insert into storage.buckets (id, name, public) 
values ('payment_proofs', 'payment_proofs', true)
on conflict (id) do nothing;

drop policy if exists "Public Select" on storage.objects;
drop policy if exists "Public Insert" on storage.objects;
drop policy if exists "Public Upload" on storage.objects;
drop policy if exists "Public Access" on storage.objects;

create policy "Public Select" on storage.objects for select using ( bucket_id = 'payment_proofs' );
create policy "Public Insert" on storage.objects for insert with check ( bucket_id = 'payment_proofs' );`;

  return (
    <div className="space-y-8 animate-slide-in-right pb-10">
      
      {/* ALERT BOX KHUSUS FIX REVIEW */}
      <div className="bg-yellow-50 border-l-4 border-yellow-500 p-6 rounded-r-xl shadow-sm">
         <div className="flex items-start gap-4">
            <div className="p-3 bg-yellow-100 text-yellow-700 rounded-full">
               <RefreshCw size={24} />
            </div>
            <div className="flex-1">
               <h3 className="text-lg font-bold text-yellow-800">Review Tidak Muncul?</h3>
               <p className="text-sm text-yellow-700 mt-1 mb-3">
                  Jika ulasan pelanggan tidak tampil di produk, kemungkinan besar akses database (RLS) ke tabel Transaksi masih tertutup. Jalankan script perbaikan ini:
               </p>
               <div className="relative group">
                  <pre className="bg-yellow-900/10 text-yellow-900 p-3 rounded-lg text-xs font-mono overflow-x-auto border border-yellow-200">
                     {fixReviewSQL}
                  </pre>
                  <button 
                     onClick={() => copyToClipboard(fixReviewSQL, 'fix')}
                     className="absolute top-2 right-2 p-2 bg-white hover:bg-yellow-100 rounded text-yellow-700 transition flex items-center gap-2 text-xs font-bold border border-yellow-200"
                  >
                     {copiedSection === 'fix' ? <Check size={14}/> : <Copy size={14}/>} 
                     {copiedSection === 'fix' ? 'Disalin!' : 'Copy Fix SQL'}
                  </button>
               </div>
            </div>
         </div>
      </div>

      <div className="bg-blue-50 border border-blue-200 rounded-2xl p-6 flex gap-4 items-start">
         <div className="p-3 bg-blue-100 text-blue-600 rounded-xl">
            <Terminal size={24} />
         </div>
         <div>
            <h3 className="text-lg font-bold text-blue-900">Setup Database Awal (Full)</h3>
            <p className="text-sm text-blue-700 mt-1 leading-relaxed">
               Jalankan script di bawah ini berurutan jika Anda baru pertama kali setup database.
            </p>
         </div>
      </div>

      <div className="grid grid-cols-1 gap-8">
         {/* STEP 1: CORE */}
         <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
            <div className="px-6 py-4 bg-gray-50 border-b border-gray-100 flex justify-between items-center">
               <h4 className="font-bold text-gray-800 flex items-center gap-2">
                  <Database size={18} className="text-nature-600"/> Bagian 1: Core Tables & Policies
               </h4>
            </div>
            <div className="p-6">
               <div className="relative group">
                  <pre className="bg-gray-900 text-gray-100 p-4 rounded-xl text-xs font-mono overflow-x-auto whitespace-pre-wrap border border-gray-700 max-h-64">
                     {coreSQL}
                  </pre>
                  <button 
                     onClick={() => copyToClipboard(coreSQL, 'core')}
                     className="absolute top-2 right-2 p-2 bg-white/10 hover:bg-white/20 rounded-lg text-white transition flex items-center gap-2 text-xs font-bold backdrop-blur-sm"
                  >
                     {copiedSection === 'core' ? <Check size={14}/> : <Copy size={14}/>} 
                     {copiedSection === 'core' ? 'Disalin!' : 'Copy SQL'}
                  </button>
               </div>
            </div>
         </div>

         {/* STEP 2: FEATURES */}
         <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
            <div className="px-6 py-4 bg-gray-50 border-b border-gray-100">
               <h4 className="font-bold text-gray-800 flex items-center gap-2">
                  <Shield size={18} className="text-blue-600"/> Bagian 2: Fitur Tambahan (Review & Logs)
               </h4>
            </div>
            <div className="p-6">
               <div className="relative group">
                  <pre className="bg-gray-900 text-gray-100 p-4 rounded-xl text-xs font-mono overflow-x-auto whitespace-pre-wrap border border-gray-700 max-h-64">
                     {featuresSQL}
                  </pre>
                  <button 
                     onClick={() => copyToClipboard(featuresSQL, 'features')}
                     className="absolute top-2 right-2 p-2 bg-white/10 hover:bg-white/20 rounded-lg text-white transition flex items-center gap-2 text-xs font-bold backdrop-blur-sm"
                  >
                     {copiedSection === 'features' ? <Check size={14}/> : <Copy size={14}/>} 
                     {copiedSection === 'features' ? 'Disalin!' : 'Copy SQL'}
                  </button>
               </div>
            </div>
         </div>

         {/* STEP 3: STORAGE */}
         <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
            <div className="px-6 py-4 bg-gray-50 border-b border-gray-100">
               <h4 className="font-bold text-gray-800 flex items-center gap-2">
                  <HardDrive size={18} className="text-orange-600"/> Bagian 3: Storage (Bukti Transfer)
               </h4>
            </div>
            <div className="p-6">
               <div className="relative group">
                  <pre className="bg-gray-900 text-gray-100 p-4 rounded-xl text-xs font-mono overflow-x-auto whitespace-pre-wrap border border-gray-700 max-h-64">
                     {storageSQL}
                  </pre>
                  <button 
                     onClick={() => copyToClipboard(storageSQL, 'storage')}
                     className="absolute top-2 right-2 p-2 bg-white/10 hover:bg-white/20 rounded-lg text-white transition flex items-center gap-2 text-xs font-bold backdrop-blur-sm"
                  >
                     {copiedSection === 'storage' ? <Check size={14}/> : <Copy size={14}/>} 
                     {copiedSection === 'storage' ? 'Disalin!' : 'Copy SQL'}
                  </button>
               </div>
            </div>
         </div>

      </div>
    </div>
  );
};

export default AdminSystemSetup;
